<a href="https://colab.research.google.com/github/zoegarm/Equipo_2_P2_Analisis/blob/main/Pregunta2_limpieza.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Equipo 2**
## **Proyecto: Cáncer de mama en México**

#### Integrantes:
- Zoé Ariel García Martínez
- Atenea De La Cruz Brito
- Juan Luis Carrillo de la Cruz

### **Pregunta de investigación 2: limpieza de datos**
#### **2. ¿Cuál es la relación entre los gastos de salud y los resultados en su política en la lucha contra el cáncer?**

##### **2.1 México**
En esta sección indagaremos cual ha sido el presupuesto para salud por estado de la República Mexicana y lo relacionaremos con los índices de mortalidad por cáncer de mama, con el fin de dilucidar si la dotación de presupuesto para combatir esta enfermedad ha sido adecuada.

In [ ]:
#Librerías
import pandas as pd
import numpy as np

####**Dataset 1:** Gasto en Salud en el Sistema Nacional de Salud, México

- **Observaciones:** Estados de la República
- **Periodo:** 1993-2017
- **Archivo:** "1._GFF_01_2017_A_CONS_O.csv"
- **Fuente:** Dirección General de Información en Salud (DGIS) Secretaría de Salud (SSA).

##### **I. Carga de datos**

In [ ]:
### PRIMER DATASET: DGIS (2019). "Gasto en Salud, 1993-2017 (miles de pesos constantes, 2017=100)"
## I.Cargar datos en formato csv
#ADVERTENCIA: Archivo en  latin-1
gasto_salud = pd.read_csv("https://raw.githubusercontent.com/Zoe-Garcia/Equipo_2_P2/main/DATA/SSA%20Mexico/1._GFF_01_2017_A_CONS_O.csv", sep=',', encoding='latin-1')
gasto_salud.head()

         Entidad Federativa     Año  ...  Unnamed: 64 Unnamed: 65
0  Estados Unidos Mexicanos  1993.0  ...          NaN         NaN
1            Aguascalientes  1993.0  ...          NaN         NaN
2           Baja California  1993.0  ...          NaN         NaN
3       Baja California Sur  1993.0  ...          NaN         NaN
4                  Campeche  1993.0  ...          NaN         NaN

[5 rows x 66 columns]

##### **II. Limpieza de datos**

In [ ]:
##. II.Conocer DDBB y limpiarla
#Conocer tipo de datos y características generales del DataFrame
gasto_salud.shape

(833, 66)

In [ ]:
#Tipo de datos
gasto_salud.dtypes

Entidad Federativa                                                object
Año                                                              float64
Producto Interno Bruto                       (Miles de pesos)    float64
Gasto Total en Salud\n(I.1 + I.2)                                 object
I.1 Gasto Público Total en Salud\n(Miles de pesos)\n(1 + 2)      float64
                                                                  ...
Unnamed: 61                                                      float64
Unnamed: 62                                                      float64
Unnamed: 63                                                      float64
Unnamed: 64                                                      float64
Unnamed: 65                                                      float64
Length: 66, dtype: object

In [ ]:
#Columnas
gasto_salud.columns

Index(['Entidad Federativa', 'Año',
       'Producto Interno Bruto                       (Miles de pesos)',
       'Gasto Total en Salud\n(I.1 + I.2)',
       'I.1 Gasto Público Total en Salud\n(Miles de pesos)\n(1 + 2)',
       '1. Gasto Total \n(A+B+C+D+E+F) con SS',
       'A. Advo. Secretaria de Salud\n(Ramo 12)', 'B. FASSA (Ramo 33)',
       'C. IMSS \nProspera', 'D. SEDENA\n(Ramo 7)', 'E. SEMAR\n(Ramo 13)',
       'F. Gasto \nEstatal', '2. Gasto Total\n(A+B+C+D+E) sin SS', 'A. IMSS',
       'B. ISSSTE', 'C. PEMEX', 'D. ISSFAM', 'E. ISSES',
       'I.2 Gasto Privado Total en Salud\n(Miles de pesos constantes)\n(A + B + C)',
       'A. Gasto de los Hogares e ISFL', 'B. Cuotas de Recuperación',
       'C. Pago de Primas', 'Gasto  público total en salud como % del PIB',
       'Gasto total en salud como % del PIB',
       'Gasto público total en salud como % del gasto total en salud',
       'Gasto público total en salud como % del gasto público total',
       'Gasto público en salud per cápita para población con seguridad social',
       'Gasto público en salud per cápita para población sin seguridad social ',
       'Gasto público en salud per cápita total',
       'Aportación federal al financiamiento de la salud de la población sin seguridad social (%)',
       'Gasto privado en salud per cápita', 'Unnamed: 31', 'Unnamed: 32',
       'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36',
       'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40',
       'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44',
       'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48',
       'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52',
       'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56',
       'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60',
       'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64',
       'Unnamed: 65'],
      dtype='object')

In [ ]:
#Contar NaN
gasto_salud.isna()

     Entidad Federativa    Año  ...  Unnamed: 64  Unnamed: 65
0                 False  False  ...         True         True
1                 False  False  ...         True         True
2                 False  False  ...         True         True
3                 False  False  ...         True         True
4                 False  False  ...         True         True
..                  ...    ...  ...          ...          ...
828               False  False  ...         True         True
829               False  False  ...         True         True
830               False  False  ...         True         True
831               False  False  ...         True         True
832                True   True  ...         True         True

[833 rows x 66 columns]

In [ ]:
#Sumar NaN por columna
gasto_salud.isna().sum(axis=0)
#Nota: Columnas "Unnamed" contienen 833 NaN

Entidad Federativa                                                 1
Año                                                                1
Producto Interno Bruto                       (Miles de pesos)      8
Gasto Total en Salud\n(I.1 + I.2)                                  1
I.1 Gasto Público Total en Salud\n(Miles de pesos)\n(1 + 2)        1
                                                                ...
Unnamed: 61                                                      833
Unnamed: 62                                                      833
Unnamed: 63                                                      833
Unnamed: 64                                                      833
Unnamed: 65                                                      833
Length: 66, dtype: int64

In [ ]:
#Sumar NaN por fila
gasto_salud.isna().sum(axis=1)

0      35
1      36
2      36
3      36
4      35
       ..
828    37
829    36
830    35
831    37
832    66
Length: 833, dtype: int64

In [ ]:
#Eliminar columnas con todos los valores NaN
gasto_salud.dropna(axis=1, how='all')
#Nota: Este proceso elimina las columnas sin datos desde 'Unnamed: 31' hasta 'Unnamed: 65'

                  Entidad Federativa  ...  Gasto privado en salud per cápita
0           Estados Unidos Mexicanos  ...                             2933.4
1                     Aguascalientes  ...                               n.d.
2                    Baja California  ...                               n.d.
3                Baja California Sur  ...                               n.d.
4                           Campeche  ...                               n.d.
..                               ...  ...                                ...
828                         Tlaxcala  ...                               n.d.
829  Veracruz de Ignacio de la Llave  ...                               n.d.
830                          Yucatán  ...                               n.d.
831                        Zacatecas  ...                               n.d.
832                              NaN  ...                                NaN

[833 rows x 31 columns]

In [ ]:
#Guardar cambios de eliminación de columnas NaN en Data Frame
gasto_salud_drop = gasto_salud.dropna(axis=1, how='all')
gasto_salud_drop

                  Entidad Federativa  ...  Gasto privado en salud per cápita
0           Estados Unidos Mexicanos  ...                             2933.4
1                     Aguascalientes  ...                               n.d.
2                    Baja California  ...                               n.d.
3                Baja California Sur  ...                               n.d.
4                           Campeche  ...                               n.d.
..                               ...  ...                                ...
828                         Tlaxcala  ...                               n.d.
829  Veracruz de Ignacio de la Llave  ...                               n.d.
830                          Yucatán  ...                               n.d.
831                        Zacatecas  ...                               n.d.
832                              NaN  ...                                NaN

[833 rows x 31 columns]

In [ ]:
#Sin embargo, aparecen valores "n.d. que son en realidad "NaN"
#Remplazar n.d. por NaN para tener el verdadero conteo de nulos
gasto_salud_drop = gasto_salud_drop.replace('n.d.', np.NaN)
gasto_salud_drop.head()

         Entidad Federativa  ...  Gasto privado en salud per cápita
0  Estados Unidos Mexicanos  ...                             2933.4
1            Aguascalientes  ...                                NaN
2           Baja California  ...                                NaN
3       Baja California Sur  ...                                NaN
4                  Campeche  ...                                NaN

[5 rows x 31 columns]

In [ ]:
#Repetir el proceso anterior de limpieza de columnas con NaN
gasto_salud_drop = gasto_salud_drop.dropna(axis=1, how='all')
gasto_salud_drop.head(4)

         Entidad Federativa  ...  Gasto privado en salud per cápita
0  Estados Unidos Mexicanos  ...                             2933.4
1            Aguascalientes  ...                                NaN
2           Baja California  ...                                NaN
3       Baja California Sur  ...                                NaN

[4 rows x 31 columns]

In [ ]:
#Eliminar filas con todos los valores NaN
gasto_salud_drop.dropna(axis=0, how='all')
#Nota: Este proceso elimina la úlitma fila sin información, índice 832

                  Entidad Federativa  ...  Gasto privado en salud per cápita
0           Estados Unidos Mexicanos  ...                             2933.4
1                     Aguascalientes  ...                                NaN
2                    Baja California  ...                                NaN
3                Baja California Sur  ...                                NaN
4                           Campeche  ...                                NaN
..                               ...  ...                                ...
827                       Tamaulipas  ...                                NaN
828                         Tlaxcala  ...                                NaN
829  Veracruz de Ignacio de la Llave  ...                                NaN
830                          Yucatán  ...                                NaN
831                        Zacatecas  ...                                NaN

[832 rows x 31 columns]

In [ ]:
#Guardar cambios de eliminación de fila NaN en Data Frame
gasto_salud_drop = gasto_salud_drop.dropna(axis=0, how='all')
gasto_salud_drop.tail()

                  Entidad Federativa  ...  Gasto privado en salud per cápita
827                       Tamaulipas  ...                                NaN
828                         Tlaxcala  ...                                NaN
829  Veracruz de Ignacio de la Llave  ...                                NaN
830                          Yucatán  ...                                NaN
831                        Zacatecas  ...                                NaN

[5 rows x 31 columns]

In [ ]:
#Contar nuevamente los NaN
gasto_salud_drop.isna().sum(axis=0)

Entidad Federativa                                                                             0
Año                                                                                            0
Producto Interno Bruto                       (Miles de pesos)                                  7
Gasto Total en Salud\n(I.1 + I.2)                                                            807
I.1 Gasto Público Total en Salud\n(Miles de pesos)\n(1 + 2)                                    0
1. Gasto Total \n(A+B+C+D+E+F) con SS                                                          0
A. Advo. Secretaria de Salud\n(Ramo 12)                                                       22
B. FASSA (Ramo 33)                                                                           172
C. IMSS \nProspera                                                                           524
D. SEDENA\n(Ramo 7)                                                                          817
E. SEMAR\n(Ramo 13)                                                                          819
F. Gasto \nEstatal                                                                           206
2. Gasto Total\n(A+B+C+D+E) sin SS                                                             7
A. IMSS                                                                                        7
B. ISSSTE                                                                                      7
C. PEMEX                                                                                     154
D. ISSFAM                                                                                    817
E. ISSES                                                                                     788
I.2 Gasto Privado Total en Salud\n(Miles de pesos constantes)\n(A + B + C)                   807
A. Gasto de los Hogares e ISFL                                                               807
B. Cuotas de Recuperación                                                                    271
C. Pago de Primas                                                                            165
Gasto  público total en salud como % del PIB                                                   7
Gasto total en salud como % del PIB                                                          807
Gasto público total en salud como % del gasto total en salud                                 775
Gasto público total en salud como % del gasto público total                                   40
Gasto público en salud per cápita para población con seguridad social                        204
Gasto público en salud per cápita para población sin seguridad social                        204
Gasto público en salud per cápita total                                                        0
Aportación federal al financiamiento de la salud de la población sin seguridad social (%)    205
Gasto privado en salud per cápita                                                            775
dtype: int64

In [ ]:
#Aún existen columnas con demasiados NaN. Asimismo, dichas columnas no son tan relevantes
#Se eliminan dichas columnas para poder tener un mejor análisis
gasto_salud_drop = gasto_salud_drop.drop(['Gasto Total en Salud\n(I.1 + I.2)', 'C. IMSS \nProspera', 'D. SEDENA\n(Ramo 7)', 'E. SEMAR\n(Ramo 13)', 'D. ISSFAM', 'E. ISSES', 'I.2 Gasto Privado Total en Salud\n(Miles de pesos constantes)\n(A + B + C)', 'A. Gasto de los Hogares e ISFL', 'Gasto total en salud como % del PIB', 'Gasto público total en salud como % del gasto total en salud', 'Gasto privado en salud per cápita'], axis=1)

In [ ]:
#Contar nuevamente los NaN
gasto_salud_drop.isna().sum(axis=0)

Entidad Federativa                                                                             0
Año                                                                                            0
Producto Interno Bruto                       (Miles de pesos)                                  7
I.1 Gasto Público Total en Salud\n(Miles de pesos)\n(1 + 2)                                    0
1. Gasto Total \n(A+B+C+D+E+F) con SS                                                          0
A. Advo. Secretaria de Salud\n(Ramo 12)                                                       22
B. FASSA (Ramo 33)                                                                           172
F. Gasto \nEstatal                                                                           206
2. Gasto Total\n(A+B+C+D+E) sin SS                                                             7
A. IMSS                                                                                        7
B. ISSSTE                                                                                      7
C. PEMEX                                                                                     154
B. Cuotas de Recuperación                                                                    271
C. Pago de Primas                                                                            165
Gasto  público total en salud como % del PIB                                                   7
Gasto público total en salud como % del gasto público total                                   40
Gasto público en salud per cápita para población con seguridad social                        204
Gasto público en salud per cápita para población sin seguridad social                        204
Gasto público en salud per cápita total                                                        0
Aportación federal al financiamiento de la salud de la población sin seguridad social (%)    205
dtype: int64

In [ ]:
#Evaluar nuevamente los NaN por fila
gasto_salud.isna().sum(axis=1)

0      35
1      36
2      36
3      36
4      35
       ..
828    37
829    36
830    35
831    37
832    66
Length: 833, dtype: int64

In [ ]:
#Identificar fila donde inicia año 2000
gasto_salud_drop.iloc[238]

Entidad Federativa                                                                           Estados Unidos Mexicanos
Año                                                                                                              2000
Producto Interno Bruto                       (Miles de pesos)                                             1.09839e+10
I.1 Gasto Público Total en Salud\n(Miles de pesos)\n(1 + 2)                                               2.84323e+08
1. Gasto Total \n(A+B+C+D+E+F) con SS                                                                     9.22211e+07
A. Advo. Secretaria de Salud\n(Ramo 12)                                                                   3.25241e+07
B. FASSA (Ramo 33)                                                                                        45666769.87
F. Gasto \nEstatal                                                                                        14030225.39
2. Gasto Total\n(A+B+C+D+E) sin SS                                                                        1.92102e+08
A. IMSS                                                                                                   1.58199e+08
B. ISSSTE                                                                                                  2.5107e+07
C. PEMEX                                                                                                   8.7958e+06
B. Cuotas de Recuperación                                                                                         NaN
C. Pago de Primas                                                                                         15242292.93
Gasto  público total en salud como % del PIB                                                                      2.6
Gasto público total en salud como % del gasto público total                                                      16.6
Gasto público en salud per cápita para población con seguridad social                                         3884.49
Gasto público en salud per cápita para población sin seguridad social                                         1792.72
Gasto público en salud per cápita total                                                                       2817.98
Aportación federal al financiamiento de la salud de la población sin seguridad social (%)                        84.8
Name: 238, dtype: object

In [ ]:
#Eliminar filas con muchos NaN, correspondientes a los años 1993-1999, para igualar periodo con el Segundo DataFrame sobre mortalidad
gasto_salud_drop = gasto_salud_drop.drop(gasto_salud_drop.index[range(238)])

In [ ]:
gasto_salud_drop

                  Entidad Federativa  ...  Aportación federal al financiamiento de la salud de la población sin seguridad social (%)
238         Estados Unidos Mexicanos  ...                                               84.8
239                   Aguascalientes  ...                                               66.0
240                  Baja California  ...                                               95.8
241              Baja California Sur  ...                                               96.0
242                         Campeche  ...                                               86.1
..                               ...  ...                                                ...
827                       Tamaulipas  ...                                               68.8
828                         Tlaxcala  ...                                               94.7
829  Veracruz de Ignacio de la Llave  ...                                               80.3
830                          Yucatán  ...                                               75.9
831                        Zacatecas  ...                                               87.5

[594 rows x 20 columns]

In [ ]:
#Evaluar nuevamente los NaN por columna
gasto_salud_drop.isna().sum(axis=0)

Entidad Federativa                                                                            0
Año                                                                                           0
Producto Interno Bruto                       (Miles de pesos)                                 0
I.1 Gasto Público Total en Salud\n(Miles de pesos)\n(1 + 2)                                   0
1. Gasto Total \n(A+B+C+D+E+F) con SS                                                         0
A. Advo. Secretaria de Salud\n(Ramo 12)                                                       0
B. FASSA (Ramo 33)                                                                            0
F. Gasto \nEstatal                                                                            1
2. Gasto Total\n(A+B+C+D+E) sin SS                                                            0
A. IMSS                                                                                       0
B. ISSSTE                                                                                     0
C. PEMEX                                                                                     93
B. Cuotas de Recuperación                                                                    33
C. Pago de Primas                                                                             0
Gasto  público total en salud como % del PIB                                                  0
Gasto público total en salud como % del gasto público total                                   0
Gasto público en salud per cápita para población con seguridad social                         0
Gasto público en salud per cápita para población sin seguridad social                         0
Gasto público en salud per cápita total                                                       0
Aportación federal al financiamiento de la salud de la población sin seguridad social (%)     0
dtype: int64

In [ ]:
#Repetir proceso de eliminación de columnas con NaN numerosas
gasto_salud_drop = gasto_salud_drop.drop(['C. PEMEX'], axis=1)
gasto_salud_drop.head(3)

           Entidad Federativa  ...  Aportación federal al financiamiento de la salud de la población sin seguridad social (%)
238  Estados Unidos Mexicanos  ...                                               84.8
239            Aguascalientes  ...                                               66.0
240           Baja California  ...                                               95.8

[3 rows x 19 columns]

In [ ]:
#Convertir en 0 los NaN de columnas 'F. Gasto \nEstatal' y 'B. Cuotas de Recuperación'
gasto_salud_drop['F. Gasto \nEstatal'] = gasto_salud_drop['F. Gasto \nEstatal'].fillna(0)
gasto_salud_drop['B. Cuotas de Recuperación'] = gasto_salud_drop['B. Cuotas de Recuperación'].fillna(0)

In [ ]:
#Evaluar nuevamente los NaN por columna
gasto_salud_drop.isna().sum(axis=0)
#Nota: Obtenemos 0 NaN

Entidad Federativa                                                                           0
Año                                                                                          0
Producto Interno Bruto                       (Miles de pesos)                                0
I.1 Gasto Público Total en Salud\n(Miles de pesos)\n(1 + 2)                                  0
1. Gasto Total \n(A+B+C+D+E+F) con SS                                                        0
A. Advo. Secretaria de Salud\n(Ramo 12)                                                      0
B. FASSA (Ramo 33)                                                                           0
F. Gasto \nEstatal                                                                           0
2. Gasto Total\n(A+B+C+D+E) sin SS                                                           0
A. IMSS                                                                                      0
B. ISSSTE                                                                                    0
B. Cuotas de Recuperación                                                                    0
C. Pago de Primas                                                                            0
Gasto  público total en salud como % del PIB                                                 0
Gasto público total en salud como % del gasto público total                                  0
Gasto público en salud per cápita para población con seguridad social                        0
Gasto público en salud per cápita para población sin seguridad social                        0
Gasto público en salud per cápita total                                                      0
Aportación federal al financiamiento de la salud de la población sin seguridad social (%)    0
dtype: int64

In [ ]:
# Tipo de datos
gasto_salud_drop.dtypes

Entidad Federativa                                                                            object
Año                                                                                          float64
Producto Interno Bruto                       (Miles de pesos)                                float64
I.1 Gasto Público Total en Salud\n(Miles de pesos)\n(1 + 2)                                  float64
1. Gasto Total \n(A+B+C+D+E+F) con SS                                                        float64
A. Advo. Secretaria de Salud\n(Ramo 12)                                                      float64
B. FASSA (Ramo 33)                                                                            object
F. Gasto \nEstatal                                                                            object
2. Gasto Total\n(A+B+C+D+E) sin SS                                                           float64
A. IMSS                                                                                      float64
B. ISSSTE                                                                                    float64
B. Cuotas de Recuperación                                                                     object
C. Pago de Primas                                                                             object
Gasto  público total en salud como % del PIB                                                 float64
Gasto público total en salud como % del gasto público total                                   object
Gasto público en salud per cápita para población con seguridad social                         object
Gasto público en salud per cápita para población sin seguridad social                         object
Gasto público en salud per cápita total                                                      float64
Aportación federal al financiamiento de la salud de la población sin seguridad social (%)     object
dtype: object

In [ ]:
#Convertir 'Año' en datetime
gasto_salud_drop['Año'] = gasto_salud_drop['Año'].apply(np.int64)
gasto_salud_drop['Año'] = pd.to_datetime(gasto_salud_drop['Año'].astype(str), format='%Y')
gasto_salud_drop.head()

           Entidad Federativa  ... Aportación federal al financiamiento de la salud de la población sin seguridad social (%)
238  Estados Unidos Mexicanos  ...                                               84.8
239            Aguascalientes  ...                                               66.0
240           Baja California  ...                                               95.8
241       Baja California Sur  ...                                               96.0
242                  Campeche  ...                                               86.1

[5 rows x 19 columns]

In [ ]:
# Nuevamente revisamos el tipo de datos
gasto_salud_drop.dtypes

Entidad Federativa                                                                                   object
Año                                                                                          datetime64[ns]
Producto Interno Bruto                       (Miles de pesos)                                       float64
I.1 Gasto Público Total en Salud\n(Miles de pesos)\n(1 + 2)                                         float64
1. Gasto Total \n(A+B+C+D+E+F) con SS                                                               float64
A. Advo. Secretaria de Salud\n(Ramo 12)                                                             float64
B. FASSA (Ramo 33)                                                                                   object
F. Gasto \nEstatal                                                                                   object
2. Gasto Total\n(A+B+C+D+E) sin SS                                                                  float64
A. IMSS                                                                                             float64
B. ISSSTE                                                                                           float64
B. Cuotas de Recuperación                                                                            object
C. Pago de Primas                                                                                    object
Gasto  público total en salud como % del PIB                                                        float64
Gasto público total en salud como % del gasto público total                                          object
Gasto público en salud per cápita para población con seguridad social                                object
Gasto público en salud per cápita para población sin seguridad social                                object
Gasto público en salud per cápita total                                                             float64
Aportación federal al financiamiento de la salud de la población sin seguridad social (%)            object
dtype: object

In [ ]:
#Convertir datos object en numéricos
gasto_salud_drop['B. FASSA (Ramo 33)'] = gasto_salud_drop['B. FASSA (Ramo 33)'].apply(np.float64)
gasto_salud_drop['F. Gasto \nEstatal'] = gasto_salud_drop['F. Gasto \nEstatal'].apply(np.float64)
gasto_salud_drop['B. Cuotas de Recuperación'] = gasto_salud_drop['B. Cuotas de Recuperación'].apply(np.float64)
gasto_salud_drop['C. Pago de Primas'] = gasto_salud_drop['C. Pago de Primas'].apply(np.float64)
gasto_salud_drop['Gasto público total en salud como % del gasto público total'] = gasto_salud_drop['Gasto público total en salud como % del gasto público total'].apply(np.float64)
gasto_salud_drop['Gasto público en salud per cápita para población con seguridad social'] = gasto_salud_drop['Gasto público en salud per cápita para población con seguridad social'].apply(np.float64)
gasto_salud_drop['Gasto público en salud per cápita para población sin seguridad social '] = gasto_salud_drop['Gasto público en salud per cápita para población sin seguridad social '].apply(np.float64)
gasto_salud_drop['Aportación federal al financiamiento de la salud de la población sin seguridad social (%)'] = gasto_salud_drop['Aportación federal al financiamiento de la salud de la población sin seguridad social (%)'].apply(np.float64)

In [ ]:
#Nuevamente revisamos el tipo de datos
gasto_salud_drop.dtypes
#Todos los tipos de datos object se modificaron correctamente a float64

Entidad Federativa                                                                                   object
Año                                                                                          datetime64[ns]
Producto Interno Bruto                       (Miles de pesos)                                       float64
I.1 Gasto Público Total en Salud\n(Miles de pesos)\n(1 + 2)                                         float64
1. Gasto Total \n(A+B+C+D+E+F) con SS                                                               float64
A. Advo. Secretaria de Salud\n(Ramo 12)                                                             float64
B. FASSA (Ramo 33)                                                                                  float64
F. Gasto \nEstatal                                                                                  float64
2. Gasto Total\n(A+B+C+D+E) sin SS                                                                  float64
A. IMSS                                                                                             float64
B. ISSSTE                                                                                           float64
B. Cuotas de Recuperación                                                                           float64
C. Pago de Primas                                                                                   float64
Gasto  público total en salud como % del PIB                                                        float64
Gasto público total en salud como % del gasto público total                                         float64
Gasto público en salud per cápita para población con seguridad social                               float64
Gasto público en salud per cápita para población sin seguridad social                               float64
Gasto público en salud per cápita total                                                             float64
Aportación federal al financiamiento de la salud de la población sin seguridad social (%)           float64
dtype: object

In [ ]:
#Dimensión del DataFrame final
gasto_salud_drop.shape
#594 x 19

(594, 19)

In [ ]:
gasto_salud_drop.columns

Index(['Entidad Federativa', 'Año',
       'Producto Interno Bruto                       (Miles de pesos)',
       'I.1 Gasto Público Total en Salud\n(Miles de pesos)\n(1 + 2)',
       '1. Gasto Total \n(A+B+C+D+E+F) con SS',
       'A. Advo. Secretaria de Salud\n(Ramo 12)', 'B. FASSA (Ramo 33)',
       'F. Gasto \nEstatal', '2. Gasto Total\n(A+B+C+D+E) sin SS', 'A. IMSS',
       'B. ISSSTE', 'B. Cuotas de Recuperación', 'C. Pago de Primas',
       'Gasto  público total en salud como % del PIB',
       'Gasto público total en salud como % del gasto público total',
       'Gasto público en salud per cápita para población con seguridad social',
       'Gasto público en salud per cápita para población sin seguridad social ',
       'Gasto público en salud per cápita total',
       'Aportación federal al financiamiento de la salud de la población sin seguridad social (%)'],
      dtype='object')

In [ ]:
#Renombrar columnas: primer paso, crear mapa
column_name_mapping = {
       'Entidad Federativa' : 'Estado', 
       'Año' : 'Año',
       'Producto Interno Bruto                       (Miles de pesos)' : 'PIB en miles de pesos',
       'I.1 Gasto Público Total en Salud\n(Miles de pesos)\n(1 + 2)' : 'Total gasto público en salud',
       '1. Gasto Total \n(A+B+C+D+E+F) con SS' : 'Subtotal no asegurados',
       'A. Advo. Secretaria de Salud\n(Ramo 12)' : 'Gasto administrativo SSA', 
       'B. FASSA (Ramo 33)' : 'Aportaciones federales',
       'F. Gasto \nEstatal' : 'Gasto estatal en salud', 
       '2. Gasto Total\n(A+B+C+D+E) sin SS' : 'Subtotal asegurados', 
       'A. IMSS' : 'IMSS',
       'B. ISSSTE' : 'ISSSTE', 
       'B. Cuotas de Recuperación' : 'Cuotas de recuperación', 
       'C. Pago de Primas' : 'Primas de seguros médicos',
       'Gasto  público total en salud como % del PIB' : 'Total gasto en salud % PIB',
       'Gasto público total en salud como % del gasto público total' : 'Total gasto en salud % gasto público',
       'Gasto público en salud per cápita para población con seguridad social' : 'Gasto en salud asegurados per cápita',
       'Gasto público en salud per cápita para población sin seguridad social ' : 'Gasto en salud no asegurados per cápita',
       'Gasto público en salud per cápita total' : 'Total gasto en salud per cápita',
       'Aportación federal al financiamiento de la salud de la población sin seguridad social (%)' : 'Aportación federal % no asegurados'
}

In [ ]:
#Renombrar columnas: segundo paso, rename
gasto_salud_rename = gasto_salud_drop.rename(columns=column_name_mapping)
gasto_salud_rename.head()

                       Estado  ... Aportación federal % no asegurados
238  Estados Unidos Mexicanos  ...                               84.8
239            Aguascalientes  ...                               66.0
240           Baja California  ...                               95.8
241       Baja California Sur  ...                               96.0
242                  Campeche  ...                               86.1

[5 rows x 19 columns]

In [ ]:
#Cambiar índice a Multi-índice jerárquico tipo: Lugar, Año
gasto_salud_rename = gasto_salud_rename.set_index(['Estado', 'Año'])

In [ ]:
#Revisar multi-índice, por ejemplo las filas correspondientes al total nacional con el índice 'Estados Unidos Mexicanos'
gasto_salud_rename.loc[('Estados Unidos Mexicanos' , )]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: PerformanceWarning: indexing past lexsort depth may impact performance.

            PIB en miles de pesos  ...  Aportación federal % no asegurados
Año                                ...
2000-01-01           1.098389e+10  ...                                84.8
2001-01-01           1.113015e+10  ...                                85.4
2002-01-01           1.135181e+10  ...                                82.8
2003-01-01           1.371616e+10  ...                                84.5
2004-01-01           1.462950e+10  ...                                84.1
2005-01-01           1.533560e+10  ...                                84.2
2006-01-01           1.638521e+10  ...                                84.5
2007-01-01           1.708843e+10  ...                                84.7
2008-01-01           1.722585e+10  ...                                83.9
2009-01-01           1.637483e+10  ...                                83.8
2010-01-01           1.723685e+10  ...                                82.0
2011-01-01           1.821639e+10  ...                                86.7
2012-01-01           1.897029e+10  ...                                88.5
2013-01-01           1.877588e+10  ...                                87.9
2014-01-01           1.936610e+10  ...                                86.9
2015-01-01           2.013161e+10  ...                                84.2
2016-01-01           2.112051e+10  ...                                84.8
2017-01-01           2.192124e+10  ...                                84.9

[18 rows x 17 columns]

#####**III. Guardar dataset limpio en csv**

In [ ]:
#Guardar csv
gasto_salud_rename.to_csv(r'/content/drive/MyDrive/ssa_gasto.csv', index = True)

#### **Dataset 2:** Mortalidad cáncer de mama, México
- **Observaciones:** Estados de la República
- **Periodo:** 2000-2015
- **Archivo:** "MortalidadCaMa2000a2015.csv"
- **Fuente:** Dirección General de Información en Salud (DGIS) Secretaría de Salud (SSA)
- **Descripción:** Defunciones de mujeres de 25 años y más por tumor maligno de mama (C50), 2000-2015

##### **I. Carga de datos**

In [ ]:
### SEGUNDO DATASET: 
## I.Cargar datos en formato csv
#NOTA: Archivo en  latin-1
mortalidad = pd.read_csv("https://raw.githubusercontent.com/Zoe-Garcia/Equipo_2_P2/main/DATA/SSA%20Mexico/MortalidadCaMa2000a2015.csv", sep=',', encoding='latin-1')
mortalidad.head()

  Entidad de Residencia  num_2000  tasa_2000  ...  tasa_2014  num_2015  tasa_2015
0              Nacional      3419       14.1  ...       17.6      6252       18.0
1        Aguascalientes        36       15.6  ...       19.2        71       20.2
2       Baja California        98       16.7  ...       19.9       213       22.0
3   Baja California Sur        20       19.1  ...       15.6        33       16.0
4              Campeche        10        6.3  ...        6.8        29       11.4

[5 rows x 33 columns]

##### **II. Limpieza de datos**

In [ ]:
##. II.Conocer DDBB y limpiarla
#Conocer tipo de datos y características generales del DataFrame
mortalidad.shape

(33, 33)

In [ ]:
#Tipo de datos
mortalidad.dtypes
#Nota: Los datos son numéricos

Entidad de Residencia     object
num_2000                   int64
tasa_2000                float64
num_2001                   int64
tasa_2001                float64
num_2002                   int64
tasa_2002                float64
num_2003                   int64
tasa_2003                float64
num_2004                   int64
tasa_2004                float64
num_2005                   int64
tasa_2005                float64
num_2006                   int64
tasa_2006                float64
num_2007                   int64
tasa_2007                float64
num_2008                   int64
tasa_2008                float64
num_2009                   int64
tasa_2009                float64
num_2010                   int64
tasa_2010                float64
num_2011                   int64
tasa_2011                float64
num_2012                   int64
tasa_2012                float64
num_2013                   int64
tasa_2013                float64
num_2014                   int64
tasa_2014                float64
num_2015                   int64
tasa_2015                float64
dtype: object

In [ ]:
#Información de DataFrame
mortalidad.info

<bound method DataFrame.info of    Entidad de Residencia  num_2000  tasa_2000  ...  tasa_2014  num_2015  tasa_2015
0               Nacional      3419       14.1  ...       17.6      6252       18.0
1         Aguascalientes        36       15.6  ...       19.2        71       20.2
2        Baja California        98       16.7  ...       19.9       213       22.0
3    Baja California Sur        20       19.1  ...       15.6        33       16.0
4               Campeche        10        6.3  ...        6.8        29       11.4
5   Coahuila de Zaragoza       114       19.7  ...       21.3       215       25.7
6                 Colima        17       12.8  ...       24.1        46       22.0
7                Chiapas        53        6.3  ...       12.2       142       10.8
8              Chihuahua       152       20.9  ...       29.9       261       24.8
9       Distrito Federal       575       22.2  ...       24.0       739       24.7
10               Durango        48       14.0  ...       17.9        92       18.9
11            Guanajuato       123       10.6  ...       17.4       277       17.0
12              Guerrero        58        8.1  ...       12.5       118       12.5
13               Hidalgo        61       10.7  ...       12.1       119       14.3
14               Jalisco       290       18.6  ...       21.8       495       22.0
15                México       368       11.8  ...       14.9       743       15.2
16   Michoacán de Ocampo       126       13.1  ...       16.4       215       16.5
17               Morelos        39        9.8  ...       13.0        98       17.1
18               Nayarit        36       16.3  ...       17.6        45       13.3
19            Nuevo León       214       21.8  ...       25.6       386       26.0
20                Oaxaca        65        7.5  ...       10.0       125       11.1
21                Puebla       117        9.6  ...       13.1       217       12.6
22  Querétaro de Arteaga        35        9.9  ...       19.2        80       14.1
23          Quintana Roo        14        7.4  ...        9.7        59       14.1
24       San Luis Potosí        56       10.1  ...       15.9       114       14.9
25               Sinaloa        93       15.4  ...       17.7       189       22.2
26                Sonora       109       19.8  ...       22.6       233       28.6
27               Tabasco        39        8.9  ...       12.3        98       14.7
28            Tamaulipas       122       17.5  ...       20.5       214       20.7
29              Tlaxcala        15        6.4  ...       12.0        42       11.7
30        Veracruz Llave       220       12.2  ...       15.7       375       15.7
31               Yucatán        52       12.6  ...       14.7        81       13.2
32             Zacatecas        44       13.5  ...       18.0        88       20.0

[33 rows x 33 columns]>

In [ ]:
#Contar los NaN por columna
mortalidad.isna().sum(axis=0)
#Nota: Este DataFrame no tiene datos nulos

Entidad de Residencia    0
num_2000                 0
tasa_2000                0
num_2001                 0
tasa_2001                0
num_2002                 0
tasa_2002                0
num_2003                 0
tasa_2003                0
num_2004                 0
tasa_2004                0
num_2005                 0
tasa_2005                0
num_2006                 0
tasa_2006                0
num_2007                 0
tasa_2007                0
num_2008                 0
tasa_2008                0
num_2009                 0
tasa_2009                0
num_2010                 0
tasa_2010                0
num_2011                 0
tasa_2011                0
num_2012                 0
tasa_2012                0
num_2013                 0
tasa_2013                0
num_2014                 0
tasa_2014                0
num_2015                 0
tasa_2015                0
dtype: int64

In [ ]:
#Cambiar nombre
mortalidad_rename = mortalidad.rename(columns={'Entidad de Residencia' : 'Estado'})
mortalidad_rename.head()

                Estado  num_2000  tasa_2000  ...  tasa_2014  num_2015  tasa_2015
0             Nacional      3419       14.1  ...       17.6      6252       18.0
1       Aguascalientes        36       15.6  ...       19.2        71       20.2
2      Baja California        98       16.7  ...       19.9       213       22.0
3  Baja California Sur        20       19.1  ...       15.6        33       16.0
4             Campeche        10        6.3  ...        6.8        29       11.4

[5 rows x 33 columns]

In [ ]:
#Cambiar índice a 'Entidad de Residencia'
mortalidad_rename = mortalidad_rename.set_index(['Estado'])

In [ ]:
#Revisar cambio
mortalidad_rename.head()

                     num_2000  tasa_2000  ...  num_2015  tasa_2015
Estado                                    ...
Nacional                 3419       14.1  ...      6252       18.0
Aguascalientes             36       15.6  ...        71       20.2
Baja California            98       16.7  ...       213       22.0
Baja California Sur        20       19.1  ...        33       16.0
Campeche                   10        6.3  ...        29       11.4

[5 rows x 32 columns]

##### **III. Guardar dataset limpio en csv**

In [ ]:
#Guardar en csv
mortalidad_rename.to_csv(r'/content/drive/MyDrive/ssa_mortalidad.csv', index = True)

##### **2.2. OCDE**

En esta sección revisaremos el gasto en salud de los países miembros de la Organización para la Cooperación y el Desarrollo Económico (OCDE), del cual forma parte México. Asimismo, revisaremos indicadores sobre la incidencia del cáncer de mama en dichos países, con el fin de relacionar el gasto devengado en materia sanitaria con las estrategias para combatir el cáncer y sus resultados.

####**Dataset 3:** Global Health Expenditure Database (GHED), OMS

- **Observaciones:** 37 países miembros
- **Periodo:** 2000-2018
- **Archivo:** "WHO_NHA_indicators.csv"
- **Fuente:** Data Explorer, Organización Mundial de la Salud (OMS).
- **Descripción:** Gasto en Salud expresado como porcentaje del PIB a precios constantes. PPP indica precio paridad de producto, es decir, está normalizado par su comparación entre países con diferentes tipos de cambio y niveles de inflación.

##### **I. Carga de datos**

In [ ]:
#Librerías
import pandas as pd
import numpy as np

### PRIMER DATASET: OMS (2021). "Global Health Expenditure Database (GHED)"
## I.Cargar datos en formato csv
gasto_ocde = pd.read_csv("https://raw.githubusercontent.com/Zoe-Garcia/Equipo_2_P2/main/DATA/OCDE/WHO_NHA_indicators.csv", sep=',')
gasto_ocde.head()

  Country                                          Indicator  ...  2017  2018
0  Canada  Current Health Expenditure (CHE) as % Gross Do...  ...    11    11
1  Canada  Current Health Expenditure (CHE) per Capita in...  ...  5023  5200
2  Canada  Domestic General Government Health Expenditure...  ...    73    73
3  Canada  Domestic Private Health Expenditure (PVT-D) as...  ...    27    27
4   Chile  Current Health Expenditure (CHE) as % Gross Do...  ...     9     9

[5 rows x 21 columns]

##### **II. Limpieza de datos**

In [ ]:
##. II.Conocer DDBB y limpiarla
#Conocer tipo de datos y características generales del DataFrame
gasto_ocde.shape

(148, 21)

In [ ]:
#Tipo de datos
gasto_ocde.dtypes

Country      object
Indicator    object
2000          int64
2001          int64
2002          int64
2003          int64
2004          int64
2005          int64
2006          int64
2007          int64
2008          int64
2009          int64
2010          int64
2011          int64
2012          int64
2013          int64
2014          int64
2015          int64
2016          int64
2017          int64
2018          int64
dtype: object

In [ ]:
#Contar NaN
gasto_ocde.isna()

     Country  Indicator   2000   2001   2002  ...   2014   2015   2016   2017   2018
0      False      False  False  False  False  ...  False  False  False  False  False
1      False      False  False  False  False  ...  False  False  False  False  False
2      False      False  False  False  False  ...  False  False  False  False  False
3      False      False  False  False  False  ...  False  False  False  False  False
4      False      False  False  False  False  ...  False  False  False  False  False
..       ...        ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
143    False      False  False  False  False  ...  False  False  False  False  False
144    False      False  False  False  False  ...  False  False  False  False  False
145    False      False  False  False  False  ...  False  False  False  False  False
146    False      False  False  False  False  ...  False  False  False  False  False
147    False      False  False  False  False  ...  False  False  False  False  False

[148 rows x 21 columns]

In [ ]:
#Sumar NaN por columna
gasto_ocde.isna().sum(axis=0)
#Nota: No hay NaN en este DataFrame

Country      0
Indicator    0
2000         0
2001         0
2002         0
2003         0
2004         0
2005         0
2006         0
2007         0
2008         0
2009         0
2010         0
2011         0
2012         0
2013         0
2014         0
2015         0
2016         0
2017         0
2018         0
dtype: int64

In [ ]:
#Mostrar lista de países (únicos)
gasto_ocde['Country'].unique()

array(['Canada', 'Chile', 'Colombia', 'Mexico',
       'United States of America', 'Austria', 'Belgium', 'Czech Republic',
       'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece',
       'Hungary', 'Iceland', 'Ireland', 'Israel', 'Italy', 'Latvia',
       'Lithuania', 'Luxembourg', 'Netherlands', 'Norway', 'Poland',
       'Portugal', 'Slovakia', 'Slovenia', 'Spain', 'Sweden',
       'Switzerland', 'Turkey', 'United Kingdom', 'Australia', 'Japan',
       'New Zealand', 'Republic of Korea'], dtype=object)

In [ ]:
#Ocurrencia por país
gasto_ocde['Country'].value_counts()

Sweden                      4
Iceland                     4
Hungary                     4
Austria                     4
Switzerland                 4
Czech Republic              4
Latvia                      4
Poland                      4
United States of America    4
Portugal                    4
Greece                      4
Slovenia                    4
France                      4
Japan                       4
Finland                     4
Ireland                     4
Germany                     4
Lithuania                   4
Norway                      4
Israel                      4
Italy                       4
Belgium                     4
Turkey                      4
Luxembourg                  4
Australia                   4
New Zealand                 4
Colombia                    4
Denmark                     4
United Kingdom              4
Mexico                      4
Netherlands                 4
Estonia                     4
Spain                       4
Chile                       4
Republic of Korea           4
Canada                      4
Slovakia                    4
Name: Country, dtype: int64

In [ ]:
#Mostrar indicadores (únicos)
gasto_ocde['Indicator'].unique()

array(['Current Health Expenditure (CHE) as % Gross Domestic Product (GDP)',
       'Current Health Expenditure (CHE) per Capita in PPP',
       'Domestic General Government Health Expenditure (GGHE-D) as % Current Health Expenditure (CHE)',
       'Domestic Private Health Expenditure (PVT-D) as % Current Health Expenditure (CHE)'],
      dtype=object)

In [ ]:
#Remplazar nombre de indicadores para que sean más entendibles y cortos
gasto_ocde['Indicator'].replace(
    to_replace=['Current Health Expenditure (CHE) as % Gross Domestic Product (GDP)',
    'Current Health Expenditure (CHE) per Capita in PPP',
    'Domestic General Government Health Expenditure (GGHE-D) as % Current Health Expenditure (CHE)',
    'Domestic Private Health Expenditure (PVT-D) as % Current Health Expenditure (CHE)'],
    value=['Gasto en Salud % PIB',
    'Gasto en Salud PPP per cápita',
    'Gasto Público % Gasto en Salud',
    'Gasto Privado % Gasto en Salud'],
    inplace=True
)

In [ ]:
#Corroborar cambios
gasto_ocde.head()

  Country                       Indicator  2000  2001  ...  2015  2016  2017  2018
0  Canada            Gasto en Salud % PIB     8     9  ...    11    11    11    11
1  Canada   Gasto en Salud PPP per cápita  2430  2618  ...  4729  4909  5023  5200
2  Canada  Gasto Público % Gasto en Salud    73    73  ...    74    73    73    73
3  Canada  Gasto Privado % Gasto en Salud    27    27  ...    26    27    27    27
4   Chile            Gasto en Salud % PIB     7     7  ...     8     9     9     9

[5 rows x 21 columns]

##### **III. Guardar dataset limpio en csv**

In [ ]:
#Guardar en csv
gasto_ocde.to_csv(r'/content/drive/MyDrive/ocde_gasto.csv', index = False)

####**Dataset 4:** Health Status: Cancer, OCDE

- **Observaciones:** 37 países miembros
- **Periodo:** 2000-2012
- **Archivo:** "HEALTH_STAT_24022021235442318.csv"
- **Fuente:** OECD Statistics technology, Organización para la Cooperación y el Desarrollo Económico (OCDE).
- **Descripción:** Variable de interés, CANCBREC | Malignant neoplasms of female breast.

##### **I. Carga de datos**

In [ ]:
### SEGUNDO DATASET: OCDE (2020). “Health Status: Cancer”
## I.Cargar datos en formato csv
cancer_ocde = pd.read_csv("https://raw.githubusercontent.com/Zoe-Garcia/Equipo_2_P2/main/DATA/OCDE/HEALTH_STAT_24022021235442318.csv", sep=',')
cancer_ocde.head()

        VAR                      Variable      UNIT  ...  Value Flag Codes Flags
0  CANCTOCA           Malignant neoplasms  PERCMTTX  ...  312.0        NaN   NaN
1  CANCTOCA           Malignant neoplasms  PERCMTTX  ...  314.1        NaN   NaN
2  CANCTOCA           Malignant neoplasms  PERCMTTX  ...  323.0        NaN   NaN
3  CANCCOLC  Malignant neoplasms of colon  PERCMTTX  ...   41.7        NaN   NaN
4  CANCCOLC  Malignant neoplasms of colon  PERCMTTX  ...   38.7        NaN   NaN

[5 rows x 11 columns]

##### **II. Limpieza de datos**

In [ ]:
##. II.Conocer DDBB y limpiarla
#Conocer tipo de datos y características generales del DataFrame
cancer_ocde.shape

(2976, 11)

In [ ]:
#Tipo de datos
cancer_ocde.dtypes

VAR            object
Variable       object
UNIT           object
Measure        object
COU            object
Country        object
YEA             int64
Year            int64
Value         float64
Flag Codes    float64
Flags         float64
dtype: object

In [ ]:
#Contar NaN
cancer_ocde.isna()

        VAR  Variable   UNIT  Measure  ...   Year  Value  Flag Codes  Flags
0     False     False  False    False  ...  False  False        True   True
1     False     False  False    False  ...  False  False        True   True
2     False     False  False    False  ...  False  False        True   True
3     False     False  False    False  ...  False  False        True   True
4     False     False  False    False  ...  False  False        True   True
...     ...       ...    ...      ...  ...    ...    ...         ...    ...
2971  False     False  False    False  ...  False  False        True   True
2972  False     False  False    False  ...  False  False        True   True
2973  False     False  False    False  ...  False  False        True   True
2974  False     False  False    False  ...  False  False        True   True
2975  False     False  False    False  ...  False  False        True   True

[2976 rows x 11 columns]

In [ ]:
#Sumar NaN por columna
cancer_ocde.isna().sum(axis=0)

VAR              0
Variable         0
UNIT             0
Measure          0
COU              0
Country          0
YEA              0
Year             0
Value            0
Flag Codes    2976
Flags         2976
dtype: int64

In [ ]:
#Eliminar columnas con todos los valores NaN
cancer_ocde.dropna(axis=1, how='all')
#Nota: Este proceso elimina las columnas sin datos 'Flags Codes' y 'Flags'

           VAR                       Variable      UNIT  ...   YEA  Year   Value
0     CANCTOCA            Malignant neoplasms  PERCMTTX  ...  2002  2002   312.0
1     CANCTOCA            Malignant neoplasms  PERCMTTX  ...  2008  2008   314.1
2     CANCTOCA            Malignant neoplasms  PERCMTTX  ...  2012  2012   323.0
3     CANCCOLC   Malignant neoplasms of colon  PERCMTTX  ...  2002  2002    41.7
4     CANCCOLC   Malignant neoplasms of colon  PERCMTTX  ...  2008  2008    38.7
...        ...                            ...       ...  ...   ...   ...     ...
2971  CANCCOLC   Malignant neoplasms of colon  NBPOPIPC  ...  2012  2012  5663.0
2972  CANCLUNC    Malignant neoplasms of lung  PERCMTTX  ...  2012  2012    26.2
2973  CANCCOLC   Malignant neoplasms of colon  INCITFTF  ...  2012  2012    18.9
2974  CANCCEIX  Malignant neoplasms of cervix  NBWOMAPF  ...  2012  2012   615.0
2975  CANCLUNC    Malignant neoplasms of lung  INCITHTH  ...  2012  2012     9.8

[2976 rows x 9 columns]

In [ ]:
#Guardar cambios de eliminación de columnas NaN en Data Frame
cancer_ocde_drop = cancer_ocde.dropna(axis=1, how='all')
cancer_ocde_drop.head()

        VAR                      Variable      UNIT  ...   YEA  Year  Value
0  CANCTOCA           Malignant neoplasms  PERCMTTX  ...  2002  2002  312.0
1  CANCTOCA           Malignant neoplasms  PERCMTTX  ...  2008  2008  314.1
2  CANCTOCA           Malignant neoplasms  PERCMTTX  ...  2012  2012  323.0
3  CANCCOLC  Malignant neoplasms of colon  PERCMTTX  ...  2002  2002   41.7
4  CANCCOLC  Malignant neoplasms of colon  PERCMTTX  ...  2008  2008   38.7

[5 rows x 9 columns]

In [ ]:
cancer_ocde_drop.columns

Index(['VAR', 'Variable', 'UNIT', 'Measure', 'COU', 'Country', 'YEA', 'Year',
       'Value'],
      dtype='object')

In [ ]:
#Eliminar columnas que repiten información o no son relevantes: 'UNIT', 'COU','YEA'
cancer_ocde_drop = cancer_ocde_drop.drop(['UNIT', 'Measure','COU','YEA'], axis=1)
cancer_ocde_drop.head()

        VAR                      Variable    Country  Year  Value
0  CANCTOCA           Malignant neoplasms  Australia  2002  312.0
1  CANCTOCA           Malignant neoplasms  Australia  2008  314.1
2  CANCTOCA           Malignant neoplasms  Australia  2012  323.0
3  CANCCOLC  Malignant neoplasms of colon  Australia  2002   41.7
4  CANCCOLC  Malignant neoplasms of colon  Australia  2008   38.7

In [ ]:
#Tipo de dato
cancer_ocde_drop.dtypes

VAR          object
Variable     object
Country      object
Year          int64
Value       float64
dtype: object

In [ ]:
#Convertir 'Year' en datetime
cancer_ocde_drop['Year'] = pd.to_datetime(cancer_ocde_drop['Year'].astype(str), format='%Y')

In [ ]:
#Tipo de dato
cancer_ocde_drop.dtypes

VAR                 object
Variable            object
Country             object
Year        datetime64[ns]
Value              float64
dtype: object

#####**III. Guardar dataset limpio en csv**

In [ ]:
#Guardar en csv
cancer_ocde_drop.to_csv(r'/content/drive/MyDrive/ocde_cancer.csv', index = False)

###**Fuentes de bases de datos:**
#####**Pregunta 2**
DGIS (9 de mayo de 2019). “Gasto en Salud, 1993-2017 (miles de pesos constantes, 2017=100)”, Dirección General de Información en Salud (DGIS) Secretaría de Salud (SSA), México. Recuperado de: http://www.dgis.salud.gob.mx/descargas/xls/1._GFF_01_2017_A_CONS_O.xlsx

DGIS (2 de diciembre de 2016). "Defunciones de mujeres de 25 años y más por tumor maligno de mama (C50), 2000-2015", Dirección General de Información en Salud (DGIS) Secretaría de Salud (SSA), México. Recuperado de: https://www.gob.mx/cms/uploads/attachment/file/269549/MortalidadCaMa2000a2015.pdf

OCDE (1 de julio de 2020). “Health Status: Cancer”, OECD Statistics technology, Organización para la Cooperación y el Desarrollo Económico (OCDE). Recuperado de: https://stats.oecd.org/index.aspx?queryid=30121#

OMS (2 de marzo de 2021). “Global Health Expenditure Database (GHED)”, Data Explorer, Organización Mundial de la Salud (OMS). Recuperado de: https://apps.who.int/nha/database/Select/Indicators/en